### ISSUE TITLE
Add missing information for "original" PPNs

### ISSUE THREAD

**Issue by BibWiss** [qurator-spk/mods4pandas#21]
By now, only the content of `<mods:identifier type="PPNanalog">` seems to be included in the output but not the equivalent information from 

```
<mods:relatedItem type="original">
	<mods:recordInfo>
		<mods:recordIdentifier source="gbv-ppn">PPNxyz</mods:recordIdentifier>
	</mods:recordInfo>
</mods:relatedItem>
```

**Comment by mikegerber** [comment]
Yeah I left that because that looked like MODS in MODS :) Have to look at more data to see if that's actually true.

**Comment by mikegerber** [comment]
@BibWiss We should also probably ask our colleagues if one field is going to replace the other in the future, because these might be redundant.  `<mods:relatedItem type="original">` also looks "more modern" than `<mods:identifier type="PPNanalog">`.

**Comment by BibWiss** [comment]
Some examples are:
* PPN668289767
* PPN3371388034
* PPN1041138024 

E.g. within [sbb-mets-PPN1041138024.xml](https://content.staatsbibliothek-berlin.de/dc/PPN1041138024.mets.xml), the corresponding identifier to its physical edition ("StaBiKat (ppn original): 310512263") is contained as:

```
<mods:relatedItem type="original">
	<mods:recordInfo>
        	<mods:recordIdentifier source="gbv-ppn">PPN310512263</mods:recordIdentifier>
        </mods:recordInfo>
</mods:relatedItem>
```

**Comment by mikegerber** [comment]
Newest mods4pandas now exports this info in new columns, e.g. here in `relatedItem-original_recordInfo_recordIdentifier` for my test data:

```
PPN1678618276             None
PPN1727545451     PPN167755803
PPN1737752050             None
PPN1769395962    PPN1769388664
PPN3348760607             None
PPN773555676      PPN537331794
Name: relatedItem-original_recordInfo_recordIdentifier, dtype: object
```

**Comment by mikegerber** [comment]
See also #22, the are a number of items which have `dnb-ppn` (and we don't handle them correctly currently).
